apiVersion: v1
kind: Service
metadata:
  name: {{ template "rlt-test.fullname" . }}
  labels:
    app: {{ template "rlt-test.name" . }}
    chart: {{ template "rlt-test.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
      nodePort: 30009
  selector:
    app: {{ template "rlt-test.name" . }}
    release: {{ .Release.Name }}
